name = "ScenTrees"
uuid = "9bd120df-771c-42ec-88b3-c561e7179d1b"
authors = ["Ruben Schlotter <ruben.schlotter@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
